[settings]
# Path for a specification in vnnlib format
;specpath = "./resources/hybrid-nncs-benchmarks/tora/spec.vnnlib"
;lastRelu  = "YES"
;# Number of iteration (time steps)
;K = 5

;specpath = "./resources/hybrid-nncs-benchmarks/navigation/spec.vnnlib"
;lastRelu  = "NO"
;# Number of iteration (time steps)
;K = 5

;specpath = "./resources/hybrid-nncs-benchmarks/navigation/spec.vnnlib"
;lastRelu  = "NO"
;# Number of iteration (time steps)
;K = 5

specpath = "./resources/hybrid-nncs-benchmarks/acc/spec.vnnlib"
lastRelu  = "NO"
# Number of iteration (time steps)
K = 50

;specpath = "./resources/hybrid-nncs-benchmarks/rotation-system/spec.vnnlib"
;lastRelu  = "YES"
;# Number of iteration (time steps)
;K = 5