[settings]
# Neural Network format (SHERLOCK/ONNX/NNET/ISHERLOCK)
nnformat = "ONNX"
# Path for a neural network file
nnpath = "./resources/nn-benchmarks/acasxu/onnx/ACASXU_run2a_1_1_batch_2000.onnx"
# Path for a specification in vnnlib format
specpath = "./resources/nn-benchmarks/acasxu/vnnlib/prop_1.vnnlib"
# Problem type REACH or SAFETY
probType = "SAFETY"
# YES if want to abstract, NO otherwise
absRequired = "NO"
# Number of abstract nodes at each hidden layer
# if absRequired is YES, otherwise ignore
numOfAbsNodes = 1
# Method type MILP/PROPAGATION
technique = "PROPAGATION"
# YES for relu on the last layer,
# NO for not applying relu on the last layer
lastRelu  = "NO"
############################################
# Following specification does not change  #
############################################
# Abstraction type
absType = "INTERVAL"
# Partition type
partitionType = "FIXED"
# Solver used for methods
solverType = "Gurobi"
