[settings]
# Neural Network format (SHERLOCK/ONNX/NNET/ISHERLOCK)
nnformat = "NNET"
# Path for a neural network file
nnpath = "./resources/nncs-benchmarks/lipsy/controller.nnet"
# Path of the dynamics file
dynpath = "./resources/nncs-benchmarks/lipsy/dynamics.ini"
# Path for a specification in vnnlib format
specpath = "./resources/nncs-benchmarks/lipsy/spec.vnnlib"
# Problem type REACH or SAFETY
probType = "REACH"
# YES if want to abstract, NO otherwise
absRequired = "YES"
# Number of abstract nodes at each hidden layer
# if absRequired is YES, otherwise ignore
numOfAbsNodes = 100
# Method type MILP/PROPAGATION
technique = "PROPAGATION"
# YES for relu on the last layer,
# NO for not applying relu on the last layer
lastRelu  = "NO"
# Number of iteration (time steps)
K = 2
############################################
# Following specification does not change  #
############################################
# Abstraction type
absType = "INTERVAL"
# Partition type
partitionType = "FIXED"
# Solver used for methods
solverType = "Gurobi"
