[settings]
# Neural Network format (SHERLOCK/ONNX/NNET/ISHERLOCK)
nnformat = "ONNX"
# Path for a neural network file
nnpath = "./resources/nncs-benchmarks/tora/controller.onnx"
# Path of the dynamics file
dynpath = "./resources/nncs-benchmarks/tora/dynamics.ini"
# Path for a specification in vnnlib format
specpath = "./resources/nncs-benchmarks/tora/spec.vnnlib"
# Problem type REACH or SAFETY
probType = "SAFETY"
# YES if want to abstract, NO otherwise
absRequired = "NO"
# Number of abstract nodes at each hidden layer
# if absRequired is YES, otherwise ignore
numOfAbsNodes = 75
# Method type MILP/PROPAGATION
technique = "MILP"
# YES for relu on the last layer,
# NO for not applying relu on the last layer
lastRelu  = "NO"
# Number of iteration (time steps)
K = 3
############################################
# Following specification does not change  #
############################################
# Abstraction type
absType = "INTERVAL"
# Partition type
partitionType = "FIXED"
# Solver used for methods
solverType = "Gurobi"
