[settings]
# Dimension of the dynamical system
# X' = AX/AX+C/AX+BU/AX+BU+C
sysDim = 4
inputDim = 2
# Matrix A for linear discrete time system AX+BU+C
matA = [[0, 0, -1.295314915, -0.509155823], [0, 0, -0.766279512,  0.860674357],[0, 0,  0, 0], [0, 0,  0, 0]]
# Matrix B for linear discrete time system AX+BU+C
# If B is not in the dynamics, use NONE
matB = [[0, 0], [0, 0], [0, 1], [1, 0]]
# Vector C for linear discrete time system AX+BU+C
# If C is not in the dynamics, use NONE
arrayC = [2.726637880, 1.613018377, -20, -20]
# Unsafe set A matrix for AX1<=b1 or AX2<=b2
listA = [[[1, 0, 0, 0]], [[-1, 0, 0, 0]], [[0, 1, 0, 0]], [[0, -1, 0, 0]], [[0, 0, 1, 0]], [[0, 0, -1, 0]], [[0, 0, 0, 1]], [[0, 0, 0, -1]]]
# column vector b for AX1<=b1 or AX2<=b2
listB = [[-0.6], [-0.6], [-0.2], [-0.2], [-0.06], [-0.06], [-0.3], [-0.3]]