[settings]
# Dimension of the dynamical system
# X' = AX/AX+C/AX+BU/AX+BU+C
sysDim = 2
inputDim = 1
# Matrix A for linear discrete time system AX+BU+C
matA = [[1, -0.001], [0, 1]]
# Matrix B for linear discrete time system AX+BU+C
# If B is not in the dynamics, use NONE
matB = [[0], [-0.1]]
# Vector C for linear discrete time system AX+BU+C
# If C is not in the dynamics, use NONE
arrayC = "NONE"
# Unsafe set A matrix for AX1<=b1 or AX2<=b2
listA = [[[1, 0]]]
# column vector b for AX1<=b1 or AX2<=b2
listB = [[1]]