[settings]
# Dimension of the dynamical system
# X' = AX/AX+C/AX+BU/AX+BU+C
sysDim = 4
inputDim = 2
# Matrix A for linear discrete time system AX+BU+C
matA = [[1, 0, 0, 1], [0, 1, 20, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
# Matrix B for linear discrete time system AX+BU+C
# If B is not in the dynamics, use NONE
matB = [[0.5, 0], [0, 10], [0, 1], [1, 0]]
# Vector C for linear discrete time system AX+BU+C
# If C is not in the dynamics, use NONE
arrayC = [0.5, 0, 0, 1]

# Unsafe set A matrix for AX1<=b1 or AX2<=b2
listA = [[[1, 0, 0, 0]], [[-1, 0, 0, 0]]]
# column vector b for AX1<=b1 or AX2<=b2
listB = [[0], [-40]]