[settings]
# Dimension of the dynamical system
# X' = AX/AX+C/AX+BU/AX+BU+C
sysDim = 2
inputDim = 1
# Matrix A for linear discrete time system AX+BU+C
matA = [[1, 2], [2, -1]]
# Matrix B for linear discrete time system AX+BU+C
# If B is not in the dynamics, use NONE
matB = [[1, 0], [0, 1]]
# Vector C for linear discrete time system AX+BU+C
# If C is not in the dynamics, use NONE
arrayC = "NONE"