[settings]
# Dimension of the dynamical system
# X' = AX/AX+C/AX+BU/AX+BU+C
sysDim = 2
inputDim = 1
# Matrix A for linear discrete time system AX+BU+C
matA = [[2.1782, 1.3683], [2.7366, 2.1782]]
# Matrix B for linear discrete time system AX+BU+C
# If B is not in the dynamics, use NONE
matB = [[4.7127], [10.9464]]
# Vector C for linear discrete time system AX+BU+C
# If C is not in the dynamics, use NONE
arrayC = [0, 0]